.TH "_Default" 3 "26 Nov 2006" "Version 1.0" "Skyline Website" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Default \- Default page of Skyline Website.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBPage_Load\fP (object sender, EventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Default page of Skyline Website. 

<author>Jarod Wen</author> <Date>20:18pm, Nov 26th, 2006</Date> 
.PP
.SH "Member Function Documentation"
.PP 
.SS "void _Default.Page_Load (object sender, EventArgs e)\fC [protected]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Skyline Website from the source code.
