.TH "E:/Documents and Settings/LeeWinnie/My Documents/Visual Studio 2005/WebSites/SkylineWebSite/App_Code/BasicSkyline.cs" 3 "26 Nov 2006" "Version 1.0" "Skyline Website" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Documents and Settings/LeeWinnie/My Documents/Visual Studio 2005/WebSites/SkylineWebSite/App_Code/BasicSkyline.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSystem\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Data\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Configuration\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Web\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Web.Security\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Web.UI\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Web.UI.WebControls\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Web.UI.WebControls.WebParts\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Web.UI.HtmlControls\fP"
.br
.ti -1c
.RI "namespace \fBSystem.Collections\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicSkyline\fP"
.br
.RI "\fI\fBBasicSkyline\fP: Basic Skyline computation using BNL. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Skyline Website from the source code.
