.TH "Skyline_NBA" 3 "26 Nov 2006" "Version 1.0" "Skyline Website" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Skyline_NBA \- Skyline query on NBA player data.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBPage_Load\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbtnQuery_Click\fP (object sender, EventArgs e)"
.br
.RI "\fIHandles the Click event of the btnQuery control. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitializeData\fP ()"
.br
.RI "\fIInitializes the data. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Skyline query on NBA player data. 

<author>Jarod Wen</author> <Date>20:20pm, Nov 26th, 2006</Date> 
.PP
.SH "Member Function Documentation"
.PP 
.SS "void Skyline_NBA.Page_Load (object sender, EventArgs e)\fC [protected]\fP"
.PP
.SS "void Skyline_NBA.InitializeData ()\fC [private]\fP"
.PP
Initializes the data. 
.PP

.SS "void Skyline_NBA.btnQuery_Click (object sender, EventArgs e)\fC [protected]\fP"
.PP
Handles the Click event of the btnQuery control. 
.PP
\fBParameters:\fP
.RS 4
\fIsender\fP The source of the event.
.br
\fIe\fP The \fBSystem.EventArgs\fP instance containing the event data.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Skyline Website from the source code.
