.TH "E:/Documents and Settings/LeeWinnie/My Documents/Visual Studio 2005/WebSites/SkylineWebSite/App_Code/SystemLog.cs" 3 "26 Nov 2006" "Version 1.0" "Skyline Website" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Documents and Settings/LeeWinnie/My Documents/Visual Studio 2005/WebSites/SkylineWebSite/App_Code/SystemLog.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSystem.IO\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSystemLog\fP"
.br
.RI "\fIManage all the errors directed to the methods in this class. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Skyline Website from the source code.
