.TH "E:/Documents and Settings/LeeWinnie/My Documents/Visual Studio 2005/WebSites/SkylineWebSite/Skyline_NBA.aspx.cs" 3 "26 Nov 2006" "Version 1.0" "Skyline Website" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Documents and Settings/LeeWinnie/My Documents/Visual Studio 2005/WebSites/SkylineWebSite/Skyline_NBA.aspx.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSystem.Data.SqlClient\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSkyline_NBA\fP"
.br
.RI "\fISkyline query on NBA player data. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Skyline Website from the source code.
