.TH "UserDefine_1" 3 "26 Nov 2006" "Version 1.0" "Skyline Website" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserDefine_1 \- User Defined skyline query: Schemes upload, select and modify.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBPage_Load\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBGridView1_SelectedIndexChanged\fP (object sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBbtnUpload_Click\fP (object sender, EventArgs e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
User Defined skyline query: Schemes upload, select and modify. 

<author>Jarod Wen</author> <Date>20:18pm, Nov 26th, 2006</Date> 
.PP
.SH "Member Function Documentation"
.PP 
.SS "void UserDefine_1.Page_Load (object sender, EventArgs e)\fC [protected]\fP"
.PP
.SS "void UserDefine_1.GridView1_SelectedIndexChanged (object sender, EventArgs e)\fC [protected]\fP"
.PP
.SS "void UserDefine_1.btnUpload_Click (object sender, EventArgs e)\fC [protected]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Skyline Website from the source code.
